
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDEALPHANUM AND BETWEEN COLUMN_REF CONTAINS DIVIDE ENDS_WITH EQUALS FLOAT GREATER GREATER_EQUAL INTEGER IS LESS LESS_EQUAL LPAREN MATCHES MINUS MULTIPLY NOT_CONTAINS NOT_EQUALS NUMBER NUMERIC PLUS REQUIRED RPAREN STARTS_WITH STRING STRING_TYPErule_statement : arithmetic_rule\n| datatype_rule\n| comparison_rule\n| pattern_rule\n| range_rule\n| validation_rulearithmetic_rule : COLUMN_REF EQUALS expressiondatatype_rule : COLUMN_REF IS datatypedatatype : ALPHANUM\n| NUMERIC\n| INTEGER\n| FLOAT\n| STRING_TYPEcomparison_rule : COLUMN_REF comparison_operator valuecomparison_operator : EQUALS\n| NOT_EQUALS\n| GREATER\n| LESS\n| GREATER_EQUAL\n| LESS_EQUALpattern_rule : COLUMN_REF pattern_operator STRINGpattern_operator : MATCHES\n| CONTAINS\n| NOT_CONTAINS\n| STARTS_WITH\n| ENDS_WITHrange_rule : COLUMN_REF BETWEEN signed_number AND signed_numbervalidation_rule : COLUMN_REF REQUIREDsigned_number : NUMBER\n| MINUS NUMBERvalue : signed_number\n| STRINGvalue : COLUMN_REFexpression : term\n| expression PLUS term\n| expression MINUS termterm : factor\n| term MULTIPLY factor\n| term DIVIDE factorfactor : signed_number\n| LPAREN expression RPARENfactor : COLUMN_REF'
    
_lr_action_items = {'COLUMN_REF':([0,9,11,15,16,17,18,19,31,45,46,47,48,],[8,25,39,-16,-17,-18,-19,-20,25,25,25,25,25,]),'$end':([1,2,3,4,5,6,7,14,25,26,27,29,30,32,33,34,35,36,37,38,39,40,41,42,43,49,52,53,54,55,56,57,],[0,-1,-2,-3,-4,-5,-6,-28,-42,-7,-34,-37,-40,-29,-8,-9,-10,-11,-12,-13,-33,-14,-31,-32,-21,-30,-35,-36,-38,-39,-41,-27,]),'EQUALS':([8,],[9,]),'IS':([8,],[10,]),'BETWEEN':([8,],[13,]),'REQUIRED':([8,],[14,]),'NOT_EQUALS':([8,],[15,]),'GREATER':([8,],[16,]),'LESS':([8,],[17,]),'GREATER_EQUAL':([8,],[18,]),'LESS_EQUAL':([8,],[19,]),'MATCHES':([8,],[20,]),'CONTAINS':([8,],[21,]),'NOT_CONTAINS':([8,],[22,]),'STARTS_WITH':([8,],[23,]),'ENDS_WITH':([8,],[24,]),'STRING':([9,11,12,15,16,17,18,19,20,21,22,23,24,],[-15,42,43,-16,-17,-18,-19,-20,-22,-23,-24,-25,-26,]),'NUMBER':([9,11,13,15,16,17,18,19,28,31,45,46,47,48,51,],[32,32,32,-16,-17,-18,-19,-20,49,32,32,32,32,32,32,]),'MINUS':([9,11,13,15,16,17,18,19,25,26,27,29,30,31,32,45,46,47,48,49,50,51,52,53,54,55,56,],[28,28,28,-16,-17,-18,-19,-20,-42,46,-34,-37,-40,28,-29,28,28,28,28,-30,46,28,-35,-36,-38,-39,-41,]),'LPAREN':([9,31,45,46,47,48,],[31,31,31,31,31,31,]),'ALPHANUM':([10,],[34,]),'NUMERIC':([10,],[35,]),'INTEGER':([10,],[36,]),'FLOAT':([10,],[37,]),'STRING_TYPE':([10,],[38,]),'MULTIPLY':([25,27,29,30,32,49,52,53,54,55,56,],[-42,47,-37,-40,-29,-30,47,47,-38,-39,-41,]),'DIVIDE':([25,27,29,30,32,49,52,53,54,55,56,],[-42,48,-37,-40,-29,-30,48,48,-38,-39,-41,]),'PLUS':([25,26,27,29,30,32,49,50,52,53,54,55,56,],[-42,45,-34,-37,-40,-29,-30,45,-35,-36,-38,-39,-41,]),'RPAREN':([25,27,29,30,32,49,50,52,53,54,55,56,],[-42,-34,-37,-40,-29,-30,56,-35,-36,-38,-39,-41,]),'AND':([32,44,49,],[-29,51,-30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rule_statement':([0,],[1,]),'arithmetic_rule':([0,],[2,]),'datatype_rule':([0,],[3,]),'comparison_rule':([0,],[4,]),'pattern_rule':([0,],[5,]),'range_rule':([0,],[6,]),'validation_rule':([0,],[7,]),'comparison_operator':([8,],[11,]),'pattern_operator':([8,],[12,]),'expression':([9,31,],[26,50,]),'term':([9,31,45,46,],[27,27,52,53,]),'factor':([9,31,45,46,47,48,],[29,29,29,29,54,55,]),'signed_number':([9,11,13,31,45,46,47,48,51,],[30,41,44,30,30,30,30,30,57,]),'datatype':([10,],[33,]),'value':([11,],[40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule_statement","S'",1,None,None,None),
  ('rule_statement -> arithmetic_rule','rule_statement',1,'p_rule_statement','dsl.py',172),
  ('rule_statement -> datatype_rule','rule_statement',1,'p_rule_statement','dsl.py',173),
  ('rule_statement -> comparison_rule','rule_statement',1,'p_rule_statement','dsl.py',174),
  ('rule_statement -> pattern_rule','rule_statement',1,'p_rule_statement','dsl.py',175),
  ('rule_statement -> range_rule','rule_statement',1,'p_rule_statement','dsl.py',176),
  ('rule_statement -> validation_rule','rule_statement',1,'p_rule_statement','dsl.py',177),
  ('arithmetic_rule -> COLUMN_REF EQUALS expression','arithmetic_rule',3,'p_arithmetic_rule','dsl.py',184),
  ('datatype_rule -> COLUMN_REF IS datatype','datatype_rule',3,'p_datatype_rule','dsl.py',189),
  ('datatype -> ALPHANUM','datatype',1,'p_datatype','dsl.py',193),
  ('datatype -> NUMERIC','datatype',1,'p_datatype','dsl.py',194),
  ('datatype -> INTEGER','datatype',1,'p_datatype','dsl.py',195),
  ('datatype -> FLOAT','datatype',1,'p_datatype','dsl.py',196),
  ('datatype -> STRING_TYPE','datatype',1,'p_datatype','dsl.py',197),
  ('comparison_rule -> COLUMN_REF comparison_operator value','comparison_rule',3,'p_comparison_rule','dsl.py',202),
  ('comparison_operator -> EQUALS','comparison_operator',1,'p_comparison_operator','dsl.py',206),
  ('comparison_operator -> NOT_EQUALS','comparison_operator',1,'p_comparison_operator','dsl.py',207),
  ('comparison_operator -> GREATER','comparison_operator',1,'p_comparison_operator','dsl.py',208),
  ('comparison_operator -> LESS','comparison_operator',1,'p_comparison_operator','dsl.py',209),
  ('comparison_operator -> GREATER_EQUAL','comparison_operator',1,'p_comparison_operator','dsl.py',210),
  ('comparison_operator -> LESS_EQUAL','comparison_operator',1,'p_comparison_operator','dsl.py',211),
  ('pattern_rule -> COLUMN_REF pattern_operator STRING','pattern_rule',3,'p_pattern_rule','dsl.py',216),
  ('pattern_operator -> MATCHES','pattern_operator',1,'p_pattern_operator','dsl.py',225),
  ('pattern_operator -> CONTAINS','pattern_operator',1,'p_pattern_operator','dsl.py',226),
  ('pattern_operator -> NOT_CONTAINS','pattern_operator',1,'p_pattern_operator','dsl.py',227),
  ('pattern_operator -> STARTS_WITH','pattern_operator',1,'p_pattern_operator','dsl.py',228),
  ('pattern_operator -> ENDS_WITH','pattern_operator',1,'p_pattern_operator','dsl.py',229),
  ('range_rule -> COLUMN_REF BETWEEN signed_number AND signed_number','range_rule',5,'p_range_rule','dsl.py',234),
  ('validation_rule -> COLUMN_REF REQUIRED','validation_rule',2,'p_validation_rule','dsl.py',239),
  ('signed_number -> NUMBER','signed_number',1,'p_signed_number','dsl.py',244),
  ('signed_number -> MINUS NUMBER','signed_number',2,'p_signed_number','dsl.py',245),
  ('value -> signed_number','value',1,'p_value','dsl.py',252),
  ('value -> STRING','value',1,'p_value','dsl.py',253),
  ('value -> COLUMN_REF','value',1,'p_value_col','dsl.py',257),
  ('expression -> term','expression',1,'p_expression','dsl.py',261),
  ('expression -> expression PLUS term','expression',3,'p_expression','dsl.py',262),
  ('expression -> expression MINUS term','expression',3,'p_expression','dsl.py',263),
  ('term -> factor','term',1,'p_term','dsl.py',270),
  ('term -> term MULTIPLY factor','term',3,'p_term','dsl.py',271),
  ('term -> term DIVIDE factor','term',3,'p_term','dsl.py',272),
  ('factor -> signed_number','factor',1,'p_factor','dsl.py',279),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','dsl.py',280),
  ('factor -> COLUMN_REF','factor',1,'p_factor_col','dsl.py',287),
]
