
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDEALPHANUM AND BETWEEN COLUMN_REF CONTAINS DIVIDE ENDS_WITH EQUALS FLOAT GREATER GREATER_EQUAL INTEGER IS LESS LESS_EQUAL LPAREN MATCHES MINUS MULTIPLY NOT_CONTAINS NOT_EQUALS NUMBER NUMERIC PLUS REQUIRED RPAREN STARTS_WITH STRING STRING_TYPErule_statement : arithmetic_rule\n| datatype_rule\n| comparison_rule\n| pattern_rule\n| range_rule\n| validation_rulearithmetic_rule : COLUMN_REF EQUALS expressiondatatype_rule : COLUMN_REF IS datatypedatatype : ALPHANUM\n| NUMERIC\n| INTEGER\n| FLOAT\n| STRING_TYPEcomparison_rule : COLUMN_REF comparison_operator valuecomparison_operator : EQUALS\n| NOT_EQUALS\n| GREATER\n| LESS\n| GREATER_EQUAL\n| LESS_EQUALpattern_rule : COLUMN_REF pattern_operator STRINGpattern_operator : MATCHES\n| CONTAINS\n| NOT_CONTAINS\n| STARTS_WITH\n| ENDS_WITHrange_rule : COLUMN_REF BETWEEN NUMBER AND NUMBERvalidation_rule : COLUMN_REF REQUIREDvalue : NUMBER\n| STRINGexpression : term\n| expression PLUS term\n| expression MINUS termterm : factor\n| term MULTIPLY factor\n| term DIVIDE factorfactor : COLUMN_REF\n| NUMBER\n| LPAREN expression RPAREN'
    
_lr_action_items = {'COLUMN_REF':([0,9,30,42,43,44,45,],[8,25,25,25,25,25,25,]),'$end':([1,2,3,4,5,6,7,14,25,26,27,28,29,31,32,33,34,35,36,37,38,39,40,48,49,50,51,52,53,],[0,-1,-2,-3,-4,-5,-6,-28,-37,-7,-31,-34,-38,-8,-9,-10,-11,-12,-13,-14,-29,-30,-21,-32,-33,-35,-36,-39,-27,]),'EQUALS':([8,],[9,]),'IS':([8,],[10,]),'BETWEEN':([8,],[13,]),'REQUIRED':([8,],[14,]),'NOT_EQUALS':([8,],[15,]),'GREATER':([8,],[16,]),'LESS':([8,],[17,]),'GREATER_EQUAL':([8,],[18,]),'LESS_EQUAL':([8,],[19,]),'MATCHES':([8,],[20,]),'CONTAINS':([8,],[21,]),'NOT_CONTAINS':([8,],[22,]),'STARTS_WITH':([8,],[23,]),'ENDS_WITH':([8,],[24,]),'NUMBER':([9,11,13,15,16,17,18,19,30,42,43,44,45,47,],[29,38,41,-16,-17,-18,-19,-20,29,29,29,29,29,53,]),'STRING':([9,11,12,15,16,17,18,19,20,21,22,23,24,],[-15,39,40,-16,-17,-18,-19,-20,-22,-23,-24,-25,-26,]),'LPAREN':([9,30,42,43,44,45,],[30,30,30,30,30,30,]),'ALPHANUM':([10,],[32,]),'NUMERIC':([10,],[33,]),'INTEGER':([10,],[34,]),'FLOAT':([10,],[35,]),'STRING_TYPE':([10,],[36,]),'MULTIPLY':([25,27,28,29,48,49,50,51,52,],[-37,44,-34,-38,44,44,-35,-36,-39,]),'DIVIDE':([25,27,28,29,48,49,50,51,52,],[-37,45,-34,-38,45,45,-35,-36,-39,]),'PLUS':([25,26,27,28,29,46,48,49,50,51,52,],[-37,42,-31,-34,-38,42,-32,-33,-35,-36,-39,]),'MINUS':([25,26,27,28,29,46,48,49,50,51,52,],[-37,43,-31,-34,-38,43,-32,-33,-35,-36,-39,]),'RPAREN':([25,27,28,29,46,48,49,50,51,52,],[-37,-31,-34,-38,52,-32,-33,-35,-36,-39,]),'AND':([41,],[47,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rule_statement':([0,],[1,]),'arithmetic_rule':([0,],[2,]),'datatype_rule':([0,],[3,]),'comparison_rule':([0,],[4,]),'pattern_rule':([0,],[5,]),'range_rule':([0,],[6,]),'validation_rule':([0,],[7,]),'comparison_operator':([8,],[11,]),'pattern_operator':([8,],[12,]),'expression':([9,30,],[26,46,]),'term':([9,30,42,43,],[27,27,48,49,]),'factor':([9,30,42,43,44,45,],[28,28,28,28,50,51,]),'datatype':([10,],[31,]),'value':([11,],[37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule_statement","S'",1,None,None,None),
  ('rule_statement -> arithmetic_rule','rule_statement',1,'p_rule_statement','dsl.py',188),
  ('rule_statement -> datatype_rule','rule_statement',1,'p_rule_statement','dsl.py',189),
  ('rule_statement -> comparison_rule','rule_statement',1,'p_rule_statement','dsl.py',190),
  ('rule_statement -> pattern_rule','rule_statement',1,'p_rule_statement','dsl.py',191),
  ('rule_statement -> range_rule','rule_statement',1,'p_rule_statement','dsl.py',192),
  ('rule_statement -> validation_rule','rule_statement',1,'p_rule_statement','dsl.py',193),
  ('arithmetic_rule -> COLUMN_REF EQUALS expression','arithmetic_rule',3,'p_arithmetic_rule','dsl.py',200),
  ('datatype_rule -> COLUMN_REF IS datatype','datatype_rule',3,'p_datatype_rule','dsl.py',206),
  ('datatype -> ALPHANUM','datatype',1,'p_datatype','dsl.py',211),
  ('datatype -> NUMERIC','datatype',1,'p_datatype','dsl.py',212),
  ('datatype -> INTEGER','datatype',1,'p_datatype','dsl.py',213),
  ('datatype -> FLOAT','datatype',1,'p_datatype','dsl.py',214),
  ('datatype -> STRING_TYPE','datatype',1,'p_datatype','dsl.py',215),
  ('comparison_rule -> COLUMN_REF comparison_operator value','comparison_rule',3,'p_comparison_rule','dsl.py',221),
  ('comparison_operator -> EQUALS','comparison_operator',1,'p_comparison_operator','dsl.py',226),
  ('comparison_operator -> NOT_EQUALS','comparison_operator',1,'p_comparison_operator','dsl.py',227),
  ('comparison_operator -> GREATER','comparison_operator',1,'p_comparison_operator','dsl.py',228),
  ('comparison_operator -> LESS','comparison_operator',1,'p_comparison_operator','dsl.py',229),
  ('comparison_operator -> GREATER_EQUAL','comparison_operator',1,'p_comparison_operator','dsl.py',230),
  ('comparison_operator -> LESS_EQUAL','comparison_operator',1,'p_comparison_operator','dsl.py',231),
  ('pattern_rule -> COLUMN_REF pattern_operator STRING','pattern_rule',3,'p_pattern_rule','dsl.py',237),
  ('pattern_operator -> MATCHES','pattern_operator',1,'p_pattern_operator','dsl.py',247),
  ('pattern_operator -> CONTAINS','pattern_operator',1,'p_pattern_operator','dsl.py',248),
  ('pattern_operator -> NOT_CONTAINS','pattern_operator',1,'p_pattern_operator','dsl.py',249),
  ('pattern_operator -> STARTS_WITH','pattern_operator',1,'p_pattern_operator','dsl.py',250),
  ('pattern_operator -> ENDS_WITH','pattern_operator',1,'p_pattern_operator','dsl.py',251),
  ('range_rule -> COLUMN_REF BETWEEN NUMBER AND NUMBER','range_rule',5,'p_range_rule','dsl.py',257),
  ('validation_rule -> COLUMN_REF REQUIRED','validation_rule',2,'p_validation_rule','dsl.py',263),
  ('value -> NUMBER','value',1,'p_value','dsl.py',269),
  ('value -> STRING','value',1,'p_value','dsl.py',270),
  ('expression -> term','expression',1,'p_expression','dsl.py',276),
  ('expression -> expression PLUS term','expression',3,'p_expression','dsl.py',277),
  ('expression -> expression MINUS term','expression',3,'p_expression','dsl.py',278),
  ('term -> factor','term',1,'p_term','dsl.py',286),
  ('term -> term MULTIPLY factor','term',3,'p_term','dsl.py',287),
  ('term -> term DIVIDE factor','term',3,'p_term','dsl.py',288),
  ('factor -> COLUMN_REF','factor',1,'p_factor','dsl.py',296),
  ('factor -> NUMBER','factor',1,'p_factor','dsl.py',297),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','dsl.py',298),
]
